// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Musico",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Musico",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.apple-samplecode.Musico",
            teamIdentifier: "S6A9QNGA6J",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources/Dashing Unicorn.ttf"),
                .process("Resources/LeeSeoyun.ttf")
                
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
